#! /bin/sh
##
## Copyright (c) Ericsson AB, 2011.
##
## All Rights Reserved. Reproduction in whole or in part is prohibited
## without the written consent of the copyright owner.
##
## ERICSSON MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE
## SUITABILITY OF THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING
## BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. ERICSSON
## SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A
## RESULT OF USING, MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS
## DERIVATIVES.
##
##

die () {
  echo "ERROR: $@"
  exit 1
}

install_rpms () {

   # change the working directory to the current script 
   cd $(dirname $0)
     
   for rpm in `ls ./rpms/*.rpm 2>/var/log/messages`
   do
     cmw-rpm-config-add $rpm || die "Failed to add $rpm"
   done

   cd -
}

install_rpms

